### PR TITLE
Fix: Sort-amd-path rule should ignore some paths (fixes #63)

### LINKED ISSUE #63: Sort-amd-path rule should ignore some paths
Paths which don't have defined their own corresponding parameter should be skipped in sorting check. They are probably at the end of the list and are just loaded because they must be preloaded. No one does anything with them, they just need to be loaded.

``` js
define([
    'foo/bar/Baz',
    'just/something/to/load/Whatever' // I just need to preload this library at this place
], function (Baz) { // no Whatever in param list, it's not needed
    /* ... */
});
```

### PR DESCRIPTION
**Pull request by obrejla**
After merge, we should probably add `getAmdCallback` private function to utils API. It has the same implementation which is used in `amd-function-arity` rule.

But this "refactoring" imho doesn't belong to a bugfix commit. It should have a separate commit to master.

### CODE REVIEW

File: lib/rules/sort-amd-paths.js [hunk 1]
```diff
@@ -50,6 +50,28 @@ module.exports = function (context) {
     }
 
     /**
+     * Determine if supplied `node` represents a function expression.
+     *
+     * @private
+     * @param  {ASTNode} node - node to test
+     * @return {Boolean} true if represents a function expression
+     */
+    function isFunctionExpression(node) {
```
Comment (cvisco) [inline lib/rules/sort-amd-paths.js:59]: this already exists in lib/utils as `isFunctionExpr`, it just needs to be exposed in the `module.exports`

Comment (cvisco) [inline lib/rules/sort-amd-paths.js:59]: but this can be taken care of as a follow-up refactor if need be

Comment (obrejla) [inline lib/rules/sort-amd-paths.js:59]: Yes I know...read my comment above.

Comment (obrejla) [inline lib/rules/sort-amd-paths.js:59]: `amd-function-arity` uses its own `isFunctionExpression` as well...thats why I suggested that following API change.

Comment (cvisco) [inline lib/rules/sort-amd-paths.js:59]: Ah yes, sorry. I read that too quickly :)

**Comment by cvisco** [comment]
@obrejla looks good. Merged. Thanks for the quick fix.
